apiVersion: v1
kind: Service
metadata:
  name: task-server
  labels:
    app: task-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: task-server
---
apiVersion: v1
kind: Service
metadata:
  name: task-server-external
  labels:
    app: task-server
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: task-server
